//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wowiebot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevChannel {
            get {
                return ((string)(this["prevChannel"]));
            }
            set {
                this["prevChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userCookie {
            get {
                return ((string)(this["userCookie"]));
            }
            set {
                this["userCookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string oauthCookie {
            get {
                return ((string)(this["oauthCookie"]));
            }
            set {
                this["oauthCookie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection quotes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["quotes"]));
            }
            set {
                this["quotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!")]
        public string prefix {
            get {
                return ((string)(this["prefix"]));
            }
            set {
                this["prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>yes</string>
  <string>no</string>
  <string>try again later</string>
  <string>maybe~</string>
  <string>idk ask scatter</string>
  <string>hecc no</string>
  <string>hecc yeah</string>
  <string>you wish</string>
  <string>signs point to yes</string>
  <string>signs point to no</string>
  <string>4 shur</string>
  <string>i know nothing don't ask me again please i'm just a young bot D:</string>
  <string>what do you think ;)</string>
  <string>yank train</string>
  <string>nuns on ripple</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection choices8Ball {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["choices8Ball"]));
            }
            set {
                this["choices8Ball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string commandsDataTableJson {
            get {
                return ((string)(this["commandsDataTableJson"]));
            }
            set {
                this["commandsDataTableJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int quoteVotersNumber {
            get {
                return ((int)(this["quoteVotersNumber"]));
            }
            set {
                this["quoteVotersNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No quotes. I guess $BROADCASTER isn\'t funny or quotable.")]
        public string emptyQuotesMessage {
            get {
                return ((string)(this["emptyQuotesMessage"]));
            }
            set {
                this["emptyQuotesMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minimumMessagesBetweenPeriodic {
            get {
                return ((int)(this["minimumMessagesBetweenPeriodic"]));
            }
            set {
                this["minimumMessagesBetweenPeriodic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You don\'t have permission to do that.")]
        public string noPermsMessage {
            get {
                return ((string)(this["noPermsMessage"]));
            }
            set {
                this["noPermsMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yo $SENDER, thanks for the $COUNT bits!")]
        public string messageForBits {
            get {
                return ((string)(this["messageForBits"]));
            }
            set {
                this["messageForBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int bitsMessageThreshold {
            get {
                return ((int)(this["bitsMessageThreshold"]));
            }
            set {
                this["bitsMessageThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Like this chatbot? You can get it for yourself! https://github.com/scatter-dev/wowiebot</string>
  <string>Be sure to leave a follow if you're enjoying the stream!</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection periodicMessagesArray {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["periodicMessagesArray"]));
            }
            set {
                this["periodicMessagesArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int periodicMessagePeriod {
            get {
                return ((int)(this["periodicMessagePeriod"]));
            }
            set {
                this["periodicMessagePeriod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$SENDER posted: $TITLE")]
        public string linkResponse {
            get {
                return ((string)(this["linkResponse"]));
            }
            set {
                this["linkResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You drop the 8-ball and it shatters irrecoverably onto the floor.")]
        public string empty8BallResponse {
            get {
                return ((string)(this["empty8BallResponse"]));
            }
            set {
                this["empty8BallResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thanks $SENDER for the $MONTHS months!")]
        public string subResponse {
            get {
                return ((string)(this["subResponse"]));
            }
            set {
                this["subResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thanks $SENDER for gifting that sub to $RECIPIENT! PogChamp")]
        public string giftSubResponse {
            get {
                return ((string)(this["giftSubResponse"]));
            }
            set {
                this["giftSubResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yo thanks $SENDER for bringing over $COUNT people!")]
        public string raidResponse {
            get {
                return ((string)(this["raidResponse"]));
            }
            set {
                this["raidResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to load video. Please tell the streamer to open the Song Requests window.")]
        public string closedSrWindowResponse {
            get {
                return ((string)(this["closedSrWindowResponse"]));
            }
            set {
                this["closedSrWindowResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("That video is not embeddable and can\'t be played in the bot window. Sorry!")]
        public string nonEmbeddableSrResponse {
            get {
                return ((string)(this["nonEmbeddableSrResponse"]));
            }
            set {
                this["nonEmbeddableSrResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Time\'s up. I guess no one thought that quote was funny.")]
        public string quoteTimerElapsedResponse {
            get {
                return ((string)(this["quoteTimerElapsedResponse"]));
            }
            set {
                this["quoteTimerElapsedResponse"] = value;
            }
        }
    }
}
